package main

import (
	"errors"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
)

const (
	sshGuestPort = 22
	sshGuestUser = "sandbox"
)

// Host keys are unique per sandbox while transport endpoints and tunnels are
// disposable. Recording by sandbox ID prevents endpoint reuse from looking
// like a host-key compromise.
func sshHostKeyAlias(id string) string { return "sandbox-" + id }

func sshOptions(alias string) []string {
	return []string{
		"HostKeyAlias=" + alias,
		"CheckHostIP=no",
		"StrictHostKeyChecking=accept-new",
		"IdentitiesOnly=yes",
	}
}

func sshArgs(id, identity, proxyCommand string, remoteCmd []string) []string {
	alias := sshHostKeyAlias(id)
	args := make([]string, 0, 12+len(remoteCmd))
	for _, opt := range sshOptions(alias) {
		args = append(args, "-o", opt)
	}
	args = append(args,
		"-o", "ProxyCommand="+proxyCommand,
		"-i", identity,
		sshGuestUser+"@"+id+".sbx.getaion.ai",
	)
	return append(args, remoteCmd...)
}

func renderSSHConfig(alias, host, identity, proxyCommand string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "Host %s\n", alias)
	fmt.Fprintf(&b, "  HostName %s\n", host)
	fmt.Fprintf(&b, "  User %s\n", sshGuestUser)
	fmt.Fprintf(&b, "  IdentityFile %s\n", identity)
	fmt.Fprintf(&b, "  ProxyCommand %s\n", proxyCommand)
	for _, opt := range sshOptions(alias) {
		key, value, _ := strings.Cut(opt, "=")
		fmt.Fprintf(&b, "  %s %s\n", key, value)
	}
	return b.String()
}

func sshCmd() *cobra.Command {
	var identity string
	cmd := &cobra.Command{
		Use:   "ssh <id> [-- <command...>]",
		Short: "SSH into a sandbox through the authenticated API",
		Long: "SSH into a sandbox as the unprivileged sandbox user.\n\n" +
			"The CLI creates a local Ed25519 key on first use, authorizes it in the\n" +
			"sandbox, and carries SSH through the authenticated API. No worker IP or\n" +
			"public SSH port is exposed.",
		Args: cobra.MinimumNArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			cmd.SilenceUsage = true
			identityPath, _, err := resolveSSHIdentity(identity)
			if err != nil {
				return err
			}
			proxy, err := sshProxyInvocation(args[0], identityPath)
			if err != nil {
				return err
			}
			return runSSH(sshArgs(args[0], identityPath, proxy, args[1:]), sshEnvironment())
		},
	}
	cmd.Flags().StringVarP(&identity, "identity", "i", "", "private key to authorize (default: ~/.ssh/id_ed25519 or ~/.ssh/sandbox_ed25519)")
	addClientFlags(cmd)
	return cmd
}

// sshProxyCmd is invoked by OpenSSH's ProxyCommand. It is intentionally a
// normal, inspectable subcommand: ssh_config generated by this CLI can reuse it
// for scp, rsync, and editor integrations.
func sshProxyCmd() *cobra.Command {
	var identity string
	cmd := &cobra.Command{
		Use:    "ssh-proxy <id>",
		Short:  "Open an authenticated SSH byte stream (used by ProxyCommand)",
		Hidden: true,
		Args:   cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			cmd.SilenceUsage = true
			_, publicKey, err := resolveSSHIdentity(identity)
			if err != nil {
				return err
			}
			_, c, err := dialClient()
			if err != nil {
				return err
			}
			if err := c.PrepareSSHTunnel(cmd.Context(), args[0], publicKey); err != nil {
				return err
			}
			conn, err := c.DialSandboxPort(cmd.Context(), args[0], sshGuestPort)
			if err != nil {
				return err
			}
			defer conn.Close()
			go func() {
				_, _ = io.Copy(conn, os.Stdin)
				if cw, ok := conn.(interface{ CloseWrite() error }); ok {
					_ = cw.CloseWrite()
				}
			}()
			_, err = io.Copy(os.Stdout, conn)
			return err
		},
	}
	cmd.Flags().StringVarP(&identity, "identity", "i", "", "private key whose public key is authorized")
	addClientFlags(cmd)
	return cmd
}

func sshConfigCmd() *cobra.Command {
	var identity string
	cmd := &cobra.Command{
		Use:   "ssh-config <id>",
		Short: "Print an ssh_config stanza backed by the CLI tunnel",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			cmd.SilenceUsage = true
			identityPath, _, err := resolveSSHIdentity(identity)
			if err != nil {
				return err
			}
			proxy, err := sshProxyInvocation(args[0], identityPath)
			if err != nil {
				return err
			}
			alias := sshHostKeyAlias(args[0])
			fmt.Print(renderSSHConfig(alias, args[0]+".sbx.getaion.ai", identityPath, proxy))
			return nil
		},
	}
	cmd.Flags().StringVarP(&identity, "identity", "i", "", "private key to authorize")
	addClientFlags(cmd)
	return cmd
}

func resolveSSHIdentity(requested string) (privatePath, publicKey string, err error) {
	path := strings.TrimSpace(requested)
	if path == "" {
		path = strings.TrimSpace(os.Getenv("SANDBOX_SSH_IDENTITY"))
	}
	autoGenerate := false
	if path == "" {
		home, homeErr := os.UserHomeDir()
		if homeErr != nil {
			return "", "", fmt.Errorf("find home directory: %w", homeErr)
		}
		preferred := filepath.Join(home, ".ssh", "id_ed25519")
		if info, statErr := os.Stat(preferred); statErr == nil && !info.IsDir() {
			path = preferred
		} else {
			path = filepath.Join(home, ".ssh", "sandbox_ed25519")
			autoGenerate = true
		}
	}
	if strings.HasSuffix(path, ".pub") {
		path = strings.TrimSuffix(path, ".pub")
	}
	abs, err := filepath.Abs(path)
	if err != nil {
		return "", "", fmt.Errorf("resolve identity path: %w", err)
	}
	if _, err := os.Stat(abs); errors.Is(err, os.ErrNotExist) && autoGenerate {
		if err := os.MkdirAll(filepath.Dir(abs), 0o700); err != nil {
			return "", "", fmt.Errorf("create SSH directory: %w", err)
		}
		keygen, err := exec.LookPath("ssh-keygen")
		if err != nil {
			return "", "", fmt.Errorf("ssh-keygen not found in PATH: %w", err)
		}
		gen := exec.Command(keygen, "-q", "-t", "ed25519", "-N", "", "-C", "sandbox-cli", "-f", abs)
		gen.Stdin, gen.Stdout, gen.Stderr = os.Stdin, os.Stdout, os.Stderr
		if err := gen.Run(); err != nil {
			return "", "", fmt.Errorf("generate SSH identity: %w", err)
		}
	} else if err != nil {
		return "", "", fmt.Errorf("read SSH identity %s: %w", abs, err)
	}
	var out []byte
	if publicFile, readErr := os.ReadFile(abs + ".pub"); readErr == nil {
		out = publicFile
	} else {
		keygen, lookupErr := exec.LookPath("ssh-keygen")
		if lookupErr != nil {
			return "", "", fmt.Errorf("ssh-keygen not found in PATH: %w", lookupErr)
		}
		derive := exec.Command(keygen, "-y", "-f", abs)
		derive.Stdin, derive.Stderr = os.Stdin, os.Stderr
		out, err = derive.Output()
		if err != nil {
			return "", "", fmt.Errorf("read public key from %s: %w", abs, err)
		}
	}
	key := strings.TrimSpace(string(out))
	if key == "" {
		return "", "", fmt.Errorf("ssh-keygen returned an empty public key for %s", abs)
	}
	return abs, key, nil
}

func sshProxyInvocation(id, identity string) (string, error) {
	executable, err := os.Executable()
	if err != nil {
		return "", fmt.Errorf("find sandbox CLI executable: %w", err)
	}
	args := []string{executable, "ssh-proxy", id, "--identity", identity}
	if apiURL != "" {
		args = append(args, "--api-url", apiURL)
	} else {
		args = append(args, "--config", cfgPath)
		if socket != "" {
			args = append(args, "--socket", socket)
		}
	}
	quoted := make([]string, len(args))
	for i, arg := range args {
		quoted[i] = shellQuote(arg)
	}
	return strings.Join(quoted, " "), nil
}

func shellQuote(value string) string {
	if value != "" && !strings.ContainsAny(value, " \t\r\n'\"\\$`!&;|<>()[]{}*?") {
		return value
	}
	return "'" + strings.ReplaceAll(value, "'", "'\"'\"'") + "'"
}

func sshEnvironment() []string {
	env := os.Environ()
	if apiURL != "" {
		env = setEnv(env, "SANDBOX_API_URL", apiURL)
	}
	if apiKey != "" {
		env = setEnv(env, "SANDBOX_API_KEY", apiKey)
	}
	return env
}

func setEnv(env []string, key, value string) []string {
	prefix := key + "="
	for i := range env {
		if strings.HasPrefix(env[i], prefix) {
			env[i] = prefix + value
			return env
		}
	}
	return append(env, prefix+value)
}

func runSSH(args, env []string) error {
	path, err := exec.LookPath("ssh")
	if err != nil {
		return fmt.Errorf("ssh client not found in PATH: %w", err)
	}
	proc := exec.Command(path, args...)
	proc.Stdin, proc.Stdout, proc.Stderr = os.Stdin, os.Stdout, os.Stderr
	proc.Env = env
	if err := proc.Run(); err != nil {
		var exitErr *exec.ExitError
		if errors.As(err, &exitErr) {
			return fmt.Errorf("ssh exited with status %d", exitErr.ExitCode())
		}
		return err
	}
	return nil
}
