#!/usr/bin/env bash
# The sandbox control plane VM: nomad server + `sandbox gateway` + Prometheus +
# nomad-autoscaler. One small non-spot e2-medium with a reserved static internal
# IP (workers retry_join it) and Tailscale (laptop access + subnet router).
#
#   ./control.sh up        # SA + static IP + create the VM
#   ./control.sh deploy    # build + push binaries/configs, install + start units
#   ./control.sh status    # unit health + tailnet IP + gateway URL
#   ./control.sh down       # delete the VM (keeps the reserved IP + SA)
#
# Run `up` once, then `deploy` (re-runnable). Workers come from mig.sh, which
# reads CONTROL_INTERNAL_IP for retry_join and the gateway URL.
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$DIR/../.." && pwd)"
# shellcheck source=config.env
source "$DIR/config.env"

NAME="${CONTROL_NAME:-sandbox-control}"
MACHINE="${CONTROL_MACHINE_TYPE:-e2-medium}"
IP="${CONTROL_INTERNAL_IP:?set CONTROL_INTERNAL_IP in config.env}"
REGION="${ZONE%-*}"
SUBNET_CIDR="${VPC_SUBNET_CIDR:-10.160.0.0/20}"
SA_NAME="sandbox-control-sa"
SA_EMAIL="${SA_NAME}@${PROJECT}.iam.gserviceaccount.com"
GW_PORT="${GW_PORT:-9090}"
PROM_PORT="${PROM_PORT:-9091}"
GRAFANA_PORT="${GRAFANA_PORT:-3000}"
GRAFANA_VERSION="${GRAFANA_VERSION:-11.1.0}"
PROM_VERSION="${PROMETHEUS_VERSION:-2.53.0}"
AUTOSCALER_VERSION="${AUTOSCALER_VERSION:-0.4.6}"
NOMAD_VERSION="${NOMAD_VERSION:-1.7.7}"
REMOTE_DIR="/home/${SSH_USER}/sandbox"
SECRETS="$DIR/fleet-secrets.env"

GC=(gcloud --project="$PROJECT")
sshx() { ssh -o BatchMode=yes -o StrictHostKeyChecking=accept-new "${SSH_USER}@$1" "${@:2}"; }

load_tokens() {
  [ -f "$SECRETS" ] && source "$SECRETS" || true
  GATEWAY_TOKEN="${GATEWAY_TOKEN:-$(openssl rand -hex 24)}"
  HOST_TOKEN="${HOST_TOKEN:-$(openssl rand -hex 24)}"
  cat > "$SECRETS" <<EOF
# Generated by control.sh / mig.sh — gitignored. Shared by the gateway unit,
# the Nomad job (host token), and the laptop CLI (--gateway-token).
GATEWAY_TOKEN=$GATEWAY_TOKEN
HOST_TOKEN=$HOST_TOKEN
EOF
}

cmd_up() {
  echo ">> Service account $SA_EMAIL (gce-mig target needs compute admin)"
  "${GC[@]}" iam service-accounts describe "$SA_EMAIL" >/dev/null 2>&1 || \
    "${GC[@]}" iam service-accounts create "$SA_NAME" --display-name="sandbox control plane"
  # The autoscaler resizes the MIG via ADC. Project-level binding needs
  # resourcemanager.projects.setIamPolicy — if denied, an admin must grant
  # roles/compute.instanceAdmin.v1 to $SA_EMAIL.
  if ! "${GC[@]}" projects add-iam-policy-binding "$PROJECT" \
      --member="serviceAccount:${SA_EMAIL}" \
      --role="roles/compute.instanceAdmin.v1" --condition=None >/dev/null 2>&1; then
    echo "   WARN: could not bind roles/compute.instanceAdmin.v1 to $SA_EMAIL."
    echo "         Ask an admin to grant it, or the autoscaler can't resize the MIG."
  fi

  echo ">> Reserve static internal IP $IP ($REGION)"
  "${GC[@]}" compute addresses describe "$NAME" --region="$REGION" >/dev/null 2>&1 || \
    "${GC[@]}" compute addresses create "$NAME" --region="$REGION" --subnet=default --addresses="$IP"

  echo ">> Create control VM $NAME ($MACHINE, non-spot)"
  local meta="ssh-user=${SSH_USER},vpc-subnet-cidr=${SUBNET_CIDR}"
  [ -n "${TAILSCALE_AUTHKEY:-}" ] && meta="${meta},tailscale-authkey=${TAILSCALE_AUTHKEY}"
  [ -n "${SSH_PUBLIC_KEY:-}" ]    && meta="${meta},ssh-pubkey=${SSH_PUBLIC_KEY}"
  "${GC[@]}" compute instances create "$NAME" \
    --zone="$ZONE" --machine-type="$MACHINE" \
    --image-family="${IMAGE_FAMILY:-ubuntu-2404-lts-amd64}" --image-project="${IMAGE_PROJECT:-ubuntu-os-cloud}" \
    --boot-disk-size=64GB --boot-disk-type=pd-ssd \
    --private-network-ip="$IP" \
    --service-account="$SA_EMAIL" --scopes=cloud-platform \
    --can-ip-forward \
    --metadata="$meta" \
    --metadata-from-file=startup-script="$DIR/startup-control.sh"
  echo ">> Created. First boot installs the sudo user + Tailscale (~30-60s)."
  echo "   Approve the subnet route ($SUBNET_CIDR) in the Tailscale admin console."
  echo "   Then: ./control.sh deploy"
}

cmd_deploy() {
  load_tokens
  local tsip
  tsip="$(sshx "$NAME" 'tailscale ip -4 | head -1' 2>/dev/null || true)"
  [ -n "$tsip" ] || { echo "error: $NAME not reachable over Tailscale yet (check startup + route approval)"; exit 1; }
  echo ">> Control VM $NAME tailnet=$tsip internal=$IP"

  echo ">> build-linux + push sandbox binary, configs, and control assets"
  ( cd "$REPO" && make build-linux )
  rsync -az -e "ssh -o BatchMode=yes -o StrictHostKeyChecking=accept-new" \
    "$REPO/bin/sandbox" "$REPO/configs" "$DIR/nomad" "$DIR/prometheus" "$DIR/grafana" \
    "${SSH_USER}@${NAME}:${REMOTE_DIR}/"

  echo ">> install Nomad server + Prometheus + autoscaler + gateway on $NAME"
  sshx "$NAME" \
    "sudo GW_TOKEN='$GATEWAY_TOKEN' HOST_TOKEN='$HOST_TOKEN' \
       CONTROL_IP='$IP' GW_PORT='$GW_PORT' PROM_PORT='$PROM_PORT' \
       PROM_VERSION='$PROM_VERSION' NOMAD_VERSION='$NOMAD_VERSION' \
       AUTOSCALER_VERSION='$AUTOSCALER_VERSION' \
       SLOTS_PER_HOST='${SLOTS_PER_HOST:-24}' HEADROOM_SLOTS='${HEADROOM_SLOTS:-12}' \
       SCALE_DOWN_WINDOW='${SCALE_DOWN_WINDOW:-15m}' \
       PROJECT='$PROJECT' ZONE='$ZONE' MIG_NAME='${MIG_NAME:-sandbox-workers}' \
       MIG_MIN='${MIG_MIN:-1}' MIG_MAX='${MIG_MAX:-8}' \
       QUEUE_WAIT='${QUEUE_WAIT:-180s}' QUEUE_MAX='${QUEUE_MAX:-4096}' \
       GRAFANA_VERSION='$GRAFANA_VERSION' GRAFANA_PORT='$GRAFANA_PORT' \
       GRAFANA_ADMIN_PASSWORD='${GRAFANA_ADMIN_PASSWORD:-sandbox}' \
       REMOTE_DIR='$REMOTE_DIR' bash -s" < "$DIR/control-install.sh"

  cmd_status
}

cmd_status() {
  local tsip
  tsip="$(sshx "$NAME" 'tailscale ip -4 | head -1' 2>/dev/null || echo '?')"
  [ -f "$SECRETS" ] && source "$SECRETS"
  echo
  echo ">> Control plane on $NAME (tailnet $tsip, internal $IP)"
  sshx "$NAME" 'for u in nomad-server sandbox-gateway prometheus nomad-autoscaler grafana; do
      printf "   %-18s %s\n" "$u" "$(systemctl is-active $u 2>/dev/null)"; done' 2>/dev/null || true
  echo
  echo ">> Drive from laptop:"
  echo "   SANDBOX_API_URL=http://${tsip}:${GW_PORT} SANDBOX_API_KEY=${GATEWAY_TOKEN:-<token>}"
  echo "   Grafana: http://${tsip}:${GRAFANA_PORT} (dashboard: Sandbox / Sandbox Fleet)"
}

cmd_down() {
  "${GC[@]}" compute instances delete "$NAME" --zone="$ZONE" --quiet
  echo ">> Deleted $NAME (reserved IP $NAME and SA $SA_EMAIL kept; remove manually if done)."
}

case "${1:-}" in
  up)     cmd_up ;;
  deploy) cmd_deploy ;;
  status) cmd_status ;;
  down)   cmd_down ;;
  *) echo "usage: $0 {up|deploy|status|down}" >&2; exit 1 ;;
esac
