#!/usr/bin/env bash
# The sandbox control plane VM: nomad server + `sandbox gateway` + Prometheus +
# Grafana. One small non-spot e2-medium with a reserved static internal
# IP (workers retry_join it) and Tailscale (laptop access + subnet router).
#
#   ./control.sh up        # SA + static IP + create the VM
#   ./control.sh deploy    # build + push binaries/configs, install + start units
#   ./control.sh status    # unit health + tailnet IP + gateway URL
#   ./control.sh down       # delete the VM (keeps the reserved IP + SA)
#
# Run `up` once, then `deploy` (re-runnable). Workers come from mig.sh, which
# reads CONTROL_INTERNAL_IP for retry_join and the gateway URL.
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$DIR/../.." && pwd)"
# shellcheck source=config.env
source "$DIR/config.env"

NAME="${CONTROL_NAME:-sandbox-control}"
SSH_HOST="${CONTROL_SSH_HOST:-$NAME}"
MACHINE="${CONTROL_MACHINE_TYPE:-e2-medium}"
IP="${CONTROL_INTERNAL_IP:?set CONTROL_INTERNAL_IP in config.env}"
REGION="${ZONE%-*}"
SUBNET_CIDR="${VPC_SUBNET_CIDR:-10.160.0.0/20}"
SA_NAME="sandbox-control-sa"
SA_EMAIL="${SA_NAME}@${PROJECT}.iam.gserviceaccount.com"
GW_PORT="${GW_PORT:-9090}"
PROM_PORT="${PROM_PORT:-9091}"
GRAFANA_PORT="${GRAFANA_PORT:-3000}"
GRAFANA_VERSION="${GRAFANA_VERSION:-11.1.0}"
LEGO_VERSION="${LEGO_VERSION:-4.21.0}"
PROM_VERSION="${PROMETHEUS_VERSION:-2.53.0}"
# gce-mig scale-out confirmation budget = scale-up blackout window (see
# config.env.example). Needs autoscaler >= 0.4.8 to take effect.
NOMAD_VERSION="${NOMAD_VERSION:-1.7.7}"
REMOTE_DIR="/home/${SSH_USER}/sandbox"
SECRETS="${FLEET_SECRETS_FILE:-$DIR/fleet-secrets.env}"

GC=(gcloud --project="$PROJECT")
sshx() {
  local host="$1"
  shift
  [ "$host" = "$NAME" ] && host="$SSH_HOST"
  ssh -o BatchMode=yes -o StrictHostKeyChecking=accept-new "${SSH_USER}@$host" "$@"
}

load_tokens() {
  [ -f "$SECRETS" ] && source "$SECRETS" || true
  GATEWAY_TOKEN="${GATEWAY_TOKEN:-$(openssl rand -hex 24)}"
  GATEWAY_CONTROL_TOKEN="${GATEWAY_CONTROL_TOKEN:-$(openssl rand -hex 24)}"
  # Third domain: the public ingress edge. It authenticates GET /route and
  # GET /raw-route, which return a worker's control token — so it must never be
  # the client token users hold as SANDBOX_API_KEY.
  GATEWAY_EDGE_TOKEN="${GATEWAY_EDGE_TOKEN:-$(openssl rand -hex 24)}"
  HOST_TOKEN="${HOST_TOKEN:-$(openssl rand -hex 24)}"
  cat > "$SECRETS" <<EOF
# Generated by control.sh / mig.sh — gitignored. Each trust domain has a
# separate credential; overlap files are the production rotation mechanism.
GATEWAY_TOKEN=$GATEWAY_TOKEN
GATEWAY_CONTROL_TOKEN=$GATEWAY_CONTROL_TOKEN
GATEWAY_EDGE_TOKEN=$GATEWAY_EDGE_TOKEN
HOST_TOKEN=$HOST_TOKEN
# Outgoing credentials during an overlap rotation. Set one to the value being
# retired: it is written as a SECOND line of that domain's token file, so both
# are accepted inbound until you clear it and re-deploy. They are regenerated
# into this file (empty when unset) so a rotation in progress is not silently
# dropped by the next control.sh run. See docs/management-security.md.
GATEWAY_TOKEN_PREV=${GATEWAY_TOKEN_PREV:-}
GATEWAY_EDGE_TOKEN_PREV=${GATEWAY_EDGE_TOKEN_PREV:-}
EOF
}

cmd_up() {
  echo ">> Service account $SA_EMAIL (gce-mig target needs compute admin)"
  "${GC[@]}" iam service-accounts describe "$SA_EMAIL" >/dev/null 2>&1 || \
    "${GC[@]}" iam service-accounts create "$SA_NAME" --display-name="sandbox control plane"
  # The autoscaler resizes the MIG via ADC. Project-level binding needs
  # resourcemanager.projects.setIamPolicy — if denied, an admin must grant
  # roles/compute.instanceAdmin.v1 to $SA_EMAIL.
  if ! "${GC[@]}" projects add-iam-policy-binding "$PROJECT" \
      --member="serviceAccount:${SA_EMAIL}" \
      --role="roles/compute.instanceAdmin.v1" --condition=None >/dev/null 2>&1; then
    echo "   WARN: could not bind roles/compute.instanceAdmin.v1 to $SA_EMAIL."
    echo "         Ask an admin to grant it, or the autoscaler can't resize the MIG."
  fi
  if [ -n "${INGRESS_BUCKET:-}" ]; then
    "${GC[@]}" storage buckets describe "gs://${INGRESS_BUCKET}" >/dev/null 2>&1 || \
      "${GC[@]}" storage buckets create "gs://${INGRESS_BUCKET}" \
        --location="$REGION" --uniform-bucket-level-access
    "${GC[@]}" storage buckets add-iam-policy-binding "gs://${INGRESS_BUCKET}" \
      --member="serviceAccount:${SA_EMAIL}" --role=roles/storage.objectAdmin >/dev/null
  fi

  echo ">> Reserve static internal IP $IP ($REGION)"
  "${GC[@]}" compute addresses describe "$NAME" --region="$REGION" >/dev/null 2>&1 || \
    "${GC[@]}" compute addresses create "$NAME" --region="$REGION" --subnet=default --addresses="$IP"

  echo ">> Create control VM $NAME ($MACHINE, non-spot)"
  local meta="ssh-user=${SSH_USER},vpc-subnet-cidr=${SUBNET_CIDR}"
  [ -n "${TAILSCALE_AUTHKEY:-}" ] && meta="${meta},tailscale-authkey=${TAILSCALE_AUTHKEY}"
  [ -n "${SSH_PUBLIC_KEY:-}" ]    && meta="${meta},ssh-pubkey=${SSH_PUBLIC_KEY}"
  "${GC[@]}" compute instances create "$NAME" \
    --zone="$ZONE" --machine-type="$MACHINE" \
    --image-family="${IMAGE_FAMILY:-ubuntu-2404-lts-amd64}" --image-project="${IMAGE_PROJECT:-ubuntu-os-cloud}" \
    --boot-disk-size=64GB --boot-disk-type=pd-ssd \
    --private-network-ip="$IP" \
    --service-account="$SA_EMAIL" --scopes=cloud-platform \
    --can-ip-forward \
    --metadata="$meta" \
    --metadata-from-file=startup-script="$DIR/startup-control.sh"
  echo ">> Created. First boot installs the sudo user + Tailscale (~30-60s)."
  echo "   Approve the subnet route ($SUBNET_CIDR) in the Tailscale admin console."
  echo "   Then: ./control.sh deploy"
}

cmd_deploy() {
  load_tokens
  local tsip
  tsip="$(sshx "$NAME" 'tailscale ip -4 | head -1' 2>/dev/null || true)"
  [ -n "$tsip" ] || { echo "error: $NAME not reachable over Tailscale yet (check startup + route approval)"; exit 1; }
  echo ">> Control VM $NAME tailnet=$tsip internal=$IP"

  echo ">> build-linux + push sandbox binary, configs, and control assets"
  ( cd "$REPO" && make build-linux )
  rsync -az -e "ssh -o BatchMode=yes -o StrictHostKeyChecking=accept-new" \
    "$REPO/bin/sandbox" "$REPO/configs" "$DIR/nomad" "$DIR/prometheus" "$DIR/grafana" \
    "$DIR/edge-cert-renew.sh" \
    "${SSH_USER}@${SSH_HOST}:${REMOTE_DIR}/"

  echo ">> install Nomad server + Prometheus + autoscaler + gateway on $NAME"
  local control_release
  control_release="$(git -C "$REPO" rev-parse --short HEAD)"
  sshx "$NAME" \
    "sudo GW_TOKEN='$GATEWAY_TOKEN' GATEWAY_CONTROL_TOKEN='$GATEWAY_CONTROL_TOKEN' \
       GATEWAY_EDGE_TOKEN='$GATEWAY_EDGE_TOKEN' HOST_TOKEN='$HOST_TOKEN' \
       GW_TOKEN_PREV='${GATEWAY_TOKEN_PREV:-}' \
       GATEWAY_EDGE_TOKEN_PREV='${GATEWAY_EDGE_TOKEN_PREV:-}' \
       SANDBOX_RELEASE='$control_release' \
       CONTROL_IP='$IP' GW_PORT='$GW_PORT' PROM_PORT='$PROM_PORT' \
       PROM_VERSION='$PROM_VERSION' NOMAD_VERSION='$NOMAD_VERSION' \
       SLOTS_PER_HOST='${SLOTS_PER_HOST:-24}' HEADROOM_SLOTS='${HEADROOM_SLOTS:-12}' \
       MEM_PER_SLOT_MIB='${MEM_PER_SLOT_MIB:-1180}' VM_MEMORY_OVERHEAD_MIB='${VM_MEMORY_OVERHEAD_MIB:-156}' \
       LEAD_SECONDS='${LEAD_SECONDS:-90}' \
       SCALE_IN_AFTER_SEC='${SCALE_IN_AFTER_SEC:-600}' \
       PROJECT='$PROJECT' ZONE='$ZONE' MIG_NAME='${MIG_NAME:-sandbox-workers}' \
       MIG_MIN='${MIG_MIN:-1}' MIG_MAX='${MIG_MAX:-8}' \
       QUEUE_WAIT='${QUEUE_WAIT:-240s}' QUEUE_MAX='${QUEUE_MAX:-4096}' \
       INGRESS_BUCKET='${INGRESS_BUCKET:-}' RAW_PUBLIC_HOST='${EDGE_DOMAIN:-}' \
       RAW_PORT_MIN='${EDGE_RAW_PORT_MIN:-20000}' RAW_PORT_MAX='${EDGE_RAW_PORT_MAX:-29999}' \
       GRAFANA_VERSION='$GRAFANA_VERSION' GRAFANA_PORT='$GRAFANA_PORT' \
       GRAFANA_ADMIN_PASSWORD='${GRAFANA_ADMIN_PASSWORD:-sandbox}' \
       LEGO_VERSION='$LEGO_VERSION' EDGE_DOMAIN='${EDGE_DOMAIN:-}' \
       EDGE_ACME_EMAIL='${EDGE_ACME_EMAIL:-}' \
       EDGE_DNS_PROVIDER='${EDGE_DNS_PROVIDER:-gcloud}' \
       EDGE_DNS_TOKEN_SECRET='${EDGE_DNS_TOKEN_SECRET:-sandbox-edge-dns-token}' \
       EDGE_CERT_SECRET='${EDGE_CERT_SECRET:-sandbox-edge-cert}' \
       EDGE_KEY_SECRET='${EDGE_KEY_SECRET:-sandbox-edge-key}' \
       REMOTE_DIR='$REMOTE_DIR' bash -s" < "$DIR/control-install.sh"

  cmd_status
}

cmd_status() {
  local tsip
  tsip="$(sshx "$NAME" 'tailscale ip -4 | head -1' 2>/dev/null || echo '?')"
  [ -f "$SECRETS" ] && source "$SECRETS"
  echo
  echo ">> Control plane on $NAME (tailnet $tsip, internal $IP)"
  sshx "$NAME" 'for u in nomad-server sandbox-gateway prometheus grafana; do
      printf "   %-18s %s\n" "$u" "$(systemctl is-active $u 2>/dev/null)"; done' 2>/dev/null || true
  echo
  echo ">> Drive from laptop:"
  echo "   SANDBOX_API_URL=http://${IP}:${GW_PORT} SANDBOX_API_KEY=${GATEWAY_TOKEN:-<token>}"
  echo "   Grafana: http://${tsip}:${GRAFANA_PORT} (dashboard: Sandbox / Sandbox Fleet)"
}

cmd_down() {
  "${GC[@]}" compute instances delete "$NAME" --zone="$ZONE" --quiet
  echo ">> Deleted $NAME (reserved IP $NAME and SA $SA_EMAIL kept; remove manually if done)."
}

# cmd_gateway ships ONLY a new `sandbox` binary + gateway unit. That is all a
# code rollout changes on the control plane; `deploy` additionally reinstalls
# and restarts nomad-server, prometheus, the autoscaler and grafana, which are
# version-pinned and unaffected. Set SANDBOX_BIN to reuse a binary that was
# already built (rollout.sh does this so a rollout compiles exactly once).
cmd_gateway() {
  load_tokens
  local release="${SANDBOX_RELEASE:-$(git -C "$REPO" rev-parse --short HEAD)}"
  local bin="${SANDBOX_BIN:-$REPO/bin/sandbox}"
  [ -x "$bin" ] || { ( cd "$REPO" && make build-linux ); bin="$REPO/bin/sandbox"; }
  echo ">> gateway -> ${release} ($(du -h "$bin" | cut -f1))"
  rsync -az -e "ssh -o BatchMode=yes -o StrictHostKeyChecking=accept-new" \
    "$bin" "${SSH_USER}@${SSH_HOST}:${REMOTE_DIR}/sandbox"
  sshx "$NAME" \
    "sudo SECTIONS=gateway GW_TOKEN='$GATEWAY_TOKEN' \
       GATEWAY_CONTROL_TOKEN='$GATEWAY_CONTROL_TOKEN' \
       GATEWAY_EDGE_TOKEN='$GATEWAY_EDGE_TOKEN' HOST_TOKEN='$HOST_TOKEN' \
       GW_TOKEN_PREV='${GATEWAY_TOKEN_PREV:-}' \
       GATEWAY_EDGE_TOKEN_PREV='${GATEWAY_EDGE_TOKEN_PREV:-}' \
       SANDBOX_RELEASE='$release' \
       CONTROL_IP='$IP' GW_PORT='$GW_PORT' \
       QUEUE_WAIT='${QUEUE_WAIT:-240s}' QUEUE_MAX='${QUEUE_MAX:-4096}' \
       PROJECT='$PROJECT' ZONE='$ZONE' MIG_NAME='${MIG_NAME:-sandbox-workers}' \
       MIG_MAX='${MIG_MAX:-8}' SLOTS_PER_HOST='${SLOTS_PER_HOST:-24}' \
       MEM_PER_SLOT_MIB='${MEM_PER_SLOT_MIB:-1180}' VM_MEMORY_OVERHEAD_MIB='${VM_MEMORY_OVERHEAD_MIB:-156}' \
       HEADROOM_SLOTS='${HEADROOM_SLOTS:-12}' \
       INGRESS_BUCKET='${INGRESS_BUCKET:-}' RAW_PUBLIC_HOST='${EDGE_DOMAIN:-}' \
       RAW_PORT_MIN='${EDGE_RAW_PORT_MIN:-20000}' RAW_PORT_MAX='${EDGE_RAW_PORT_MAX:-29999}' \
       REMOTE_DIR='$REMOTE_DIR' bash -s" < "$DIR/control-install.sh"
}

case "${1:-}" in
  up)      cmd_up ;;
  deploy)  cmd_deploy ;;
  gateway) cmd_gateway ;;
  status)  cmd_status ;;
  down)    cmd_down ;;
  *) echo "usage: $0 {up|deploy|gateway|status|down}" >&2; exit 1 ;;
esac
