#!/usr/bin/env bash
# Bootstrap + run the sandbox fleet on the GCP test VMs (testvm-1, testvm-2).
#
#   ./fleet-deploy.sh            # build, sync, bootstrap every host, install+start systemd units
#   ./fleet-deploy.sh status     # show unit status + tailnet IPs + gateway token
#   ./fleet-deploy.sh restart     # daemon-reload + restart the units (no rebuild/bootstrap)
#
# Prereqs: VMs already created (./vms.sh up) and reachable over Tailscale SSH,
# passwordless sudo on the guests (startup.sh sets this up), and a local Go
# toolchain (for `make build-linux`). Idempotent — safe to re-run; the
# ~5-min rootfs build inside gcp-host-bootstrap.sh only happens on first run.
#
# Topology (see memory gcp-sandbox-fleet):
#   - GATEWAY_HOST (testvm-1): runs BOTH `sandbox gateway` (:9090) and
#     `sandbox serve` (:8080, a Firecracker host).
#   - every other host: runs `sandbox serve` (:8080) only.
# Hosts heartbeat to the gateway over their Tailscale IPs. Drive the fleet from
# the laptop: point the CLI at http://<testvm-1-tailnet-ip>:9090 with the
# gateway token printed at the end (also saved to fleet-secrets.env).
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$DIR/../.." && pwd)"
# shellcheck source=config.env
source "$DIR/config.env"

GATEWAY_HOST="${GATEWAY_HOST:-testvm-1}"
CONFIG="configs/devbox-gcp.json"
GW_PORT="${GW_PORT:-9090}"
HOST_PORT="${HOST_PORT:-8080}"
REMOTE_DIR="/home/${SSH_USER}/sandbox"
SECRETS="$DIR/fleet-secrets.env"

sshx() { ssh -o BatchMode=yes -o StrictHostKeyChecking=accept-new "${SSH_USER}@$1" "${@:2}"; }

# --- tokens: generate once, persist so re-runs (and the laptop CLI) are stable ---
load_tokens() {
  [ -f "$SECRETS" ] && source "$SECRETS" || true
  GATEWAY_TOKEN="${GATEWAY_TOKEN:-$(openssl rand -hex 24)}"
  HOST_TOKEN="${HOST_TOKEN:-$(openssl rand -hex 24)}"
  cat > "$SECRETS" <<EOF
# Generated by fleet-deploy.sh — gitignored. Used by the systemd units on the
# hosts and by the laptop CLI (--gateway-token \$GATEWAY_TOKEN).
GATEWAY_TOKEN=$GATEWAY_TOKEN
HOST_TOKEN=$HOST_TOKEN
EOF
}

# --- resolve each host's Tailscale IP (units bind/advertise on the tailnet) ---
declare -A TSIP
resolve_ips() {
  for h in "${NAMES[@]}"; do
    TSIP[$h]="$(sshx "$h" 'tailscale ip -4 | head -1')"
    [ -n "${TSIP[$h]}" ] || { echo "error: no tailnet IP for $h" >&2; exit 1; }
  done
  GW_IP="${TSIP[$GATEWAY_HOST]}"
  GW_URL="http://${GW_IP}:${GW_PORT}"
}

write_serve_unit() {
  local h="$1" ip="${TSIP[$1]}"
  sshx "$h" "sudo tee /etc/systemd/system/sandbox-serve.service >/dev/null" <<EOF
[Unit]
Description=sandbox Firecracker host (serve)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
WorkingDirectory=${REMOTE_DIR}
ExecStart=${REMOTE_DIR}/sandbox serve --config ${CONFIG} \\
  --listen ${ip}:${HOST_PORT} --token ${HOST_TOKEN} \\
  --gateway ${GW_URL} --gateway-token ${GATEWAY_TOKEN} --advertise ${ip}:${HOST_PORT}
Restart=always
RestartSec=2

[Install]
WantedBy=multi-user.target
EOF
}

write_gateway_unit() {
  sshx "$GATEWAY_HOST" "sudo tee /etc/systemd/system/sandbox-gateway.service >/dev/null" <<EOF
[Unit]
Description=sandbox multi-host gateway (control plane)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
WorkingDirectory=${REMOTE_DIR}
ExecStart=${REMOTE_DIR}/sandbox gateway --listen ${GW_IP}:${GW_PORT} --token ${GATEWAY_TOKEN}
Restart=always
RestartSec=2

[Install]
WantedBy=multi-user.target
EOF
}

cmd_deploy() {
  load_tokens
  resolve_ips
  echo ">> Fleet: ${NAMES[*]} | gateway on ${GATEWAY_HOST} (${GW_URL})"

  echo ">> Building linux binaries locally"
  ( cd "$REPO" && make build-linux )

  # Sync + bootstrap each host in parallel (the rootfs build is the slow part).
  for h in "${NAMES[@]}"; do
    ( set -euo pipefail
      echo "   [$h] rsync binaries + configs + scripts"
      rsync -az -e "ssh -o BatchMode=yes -o StrictHostKeyChecking=accept-new" \
        "$REPO/bin/sandbox" "$REPO/bin/sandboxd" "$REPO/Makefile" \
        "$REPO/configs" "$REPO/scripts" \
        "${SSH_USER}@${h}:${REMOTE_DIR}/"
      echo "   [$h] host bootstrap (firecracker/kernel/rootfs — ~5 min first run)"
      sshx "$h" "cd ${REMOTE_DIR} && bash scripts/gcp-host-bootstrap.sh"
      echo "   [$h] bootstrap done"
    ) >"/tmp/fleet-deploy-$h.log" 2>&1 &
  done
  echo ">> Bootstrapping in parallel; tail /tmp/fleet-deploy-<host>.log for progress"
  wait
  for h in "${NAMES[@]}"; do echo "   --- tail $h ---"; tail -3 "/tmp/fleet-deploy-$h.log"; done

  echo ">> Installing + starting systemd units"
  write_gateway_unit
  sshx "$GATEWAY_HOST" 'sudo systemctl daemon-reload && sudo systemctl enable --now sandbox-gateway'
  for h in "${NAMES[@]}"; do
    write_serve_unit "$h"
    sshx "$h" 'sudo systemctl daemon-reload && sudo systemctl enable --now sandbox-serve'
  done

  cmd_status
}

cmd_status() {
  resolve_ips 2>/dev/null || true
  [ -f "$SECRETS" ] && source "$SECRETS"
  echo
  echo ">> Fleet status"
  for h in "${NAMES[@]}"; do
    echo "   [$h] ${TSIP[$h]:-?}  serve=$(sshx "$h" 'systemctl is-active sandbox-serve' 2>/dev/null)$( [ "$h" = "$GATEWAY_HOST" ] && echo "  gateway=$(sshx "$h" 'systemctl is-active sandbox-gateway' 2>/dev/null)")"
  done
  echo
  echo ">> Drive from laptop:"
  echo "   SANDBOX_API_URL=http://${GW_IP:-<tv1-ip>}:${GW_PORT} SANDBOX_API_KEY=${GATEWAY_TOKEN:-<token>} \\"
  echo "     tsx sdk/typescript/benchmarks/fleet-bench.ts --count 32"
}

cmd_restart() {
  resolve_ips
  sshx "$GATEWAY_HOST" 'sudo systemctl daemon-reload && sudo systemctl restart sandbox-gateway'
  for h in "${NAMES[@]}"; do sshx "$h" 'sudo systemctl restart sandbox-serve'; done
  cmd_status
}

case "${1:-deploy}" in
  deploy)  cmd_deploy ;;
  status)  cmd_status ;;
  restart) cmd_restart ;;
  *) echo "usage: $0 {deploy|status|restart}" >&2; exit 1 ;;
esac
