package gateway

// Bounded negative cache for "no host anywhere has a durable record of this
// sandbox id" (audit X12). The previous implementation was a bare sync.Map
// pruned only when an entry was HIT, so a flood of DISTINCT ids grew it
// forever — and distinct ids are trivially generated by anyone who can reach
// the public edge, which resolves every unknown hostname through
// GET /route/{id}. The ceiling here is structural, not a periodic patch: each
// insert first retires expired entries from the head of the insertion queue and
// then, if the cap is still reached, evicts the oldest survivor.
//
// Dropping an entry early is harmless — it costs at most one extra adopt probe,
// which is itself rate-limited (see adoptLimiter). Growing without a ceiling is
// not: this map is the only per-id state the gateway keeps for ids it has never
// owned.

import (
	"sync"
	"time"
)

type negCache struct {
	ttl time.Duration
	max int

	mu     sync.Mutex
	expiry map[string]time.Time
	// order is insertion order for eviction. It may name ids no longer in
	// expiry (hit-expired or explicitly dropped); those are skipped on eviction
	// and compacted away once order grows past twice the cap, so its length is
	// bounded too.
	order []string
}

func newNegCache(ttl time.Duration, max int) *negCache {
	return &negCache{ttl: ttl, max: max, expiry: make(map[string]time.Time)}
}

// has reports whether id is currently known-absent. An expired entry is deleted
// on the way out, so a repeatedly-polled dead id doesn't pin a stale verdict.
func (c *negCache) has(id string) bool {
	c.mu.Lock()
	defer c.mu.Unlock()
	exp, ok := c.expiry[id]
	if !ok {
		return false
	}
	if time.Now().Before(exp) {
		return true
	}
	delete(c.expiry, id)
	return false
}

// add records id as known-absent for the cache's TTL, evicting as needed to
// stay at or under the cap.
func (c *negCache) add(id string) {
	c.mu.Lock()
	defer c.mu.Unlock()
	now := time.Now()
	if _, dup := c.expiry[id]; !dup {
		c.order = append(c.order, id)
	}
	c.expiry[id] = now.Add(c.ttl)

	// Retire anything already expired at the head, then force the cap.
	for len(c.order) > 0 {
		head := c.order[0]
		exp, live := c.expiry[head]
		if live && now.Before(exp) && len(c.expiry) <= c.max {
			break
		}
		if live {
			delete(c.expiry, head)
		}
		c.order = c.order[1:] // stale queue entry, or evicted above
	}
	if len(c.order) > 2*c.max {
		kept := c.order[:0]
		for _, id := range c.order {
			if _, live := c.expiry[id]; live {
				kept = append(kept, id)
			}
		}
		c.order = kept
	}
}

// drop forgets id — called when a host reports it after all (a route landed),
// so a stale negative can't outlive the truth.
func (c *negCache) drop(id string) {
	c.mu.Lock()
	delete(c.expiry, id)
	c.mu.Unlock()
}

// len is the number of live-or-not-yet-swept entries; exported as a metric so
// the ceiling is observable rather than assumed.
func (c *negCache) len() int {
	c.mu.Lock()
	defer c.mu.Unlock()
	return len(c.expiry)
}
